### ISSUE TITLE
As a Data Scientist, I want to be able to analyze how to optimize the next model focusing on the R square value, so that I can optimize the future models better.   

### ISSUE THREAD

**Issue by saurabhsainani** [ivm25/marketing_mix_modelling#2]
Estimation: 
1

Acceptance criteria
- Which Key variable had the best R square value, this Goes on the top. 
- In the table chart, R square value is highlighted. 
- Clearly specify which adstock scenario was used.

**Comment by ivm25** [comment]
- Which Key variable had the best R square value, this Goes on the top.
   - **Implemented, with Search media having the highest R square value.**

-In the table chart, R square value is highlighted.
   - **Have been able to highlight the whole row (consisting of the R square value). Will have to see how that looks with everything else.**

 - Clearly specify which adstock scenario was used.
    - **Implemented.** 

Here is the latest version:

-https://marketingmixmodelling-dashexample.onrender.com/

**Comment by ivm25** [comment]
Which Key variable had the best R square value, this Goes on the top.

**Implemented, with Search media having the highest R square value.**


-In the table chart, R square value is highlighted.

**Have been able to highlight the whole row (consisting of the R square value). Will have to see how that looks with everything else.**

Clearly specify which adstock scenario was used.

**Implemented.**

Latest version:
https://marketingmixmodelling-dashexample.onrender.com/
