### ISSUE TITLE
As a business stakeholder, I want to be able to understand the patterns, trends, and seasonality of key marketing & sales metrics over time so that I can take better informed decisions.

### ISSUE THREAD

**Issue by saurabhsainani** [ivm25/marketing_mix_modelling#4]
Estimation: 
5 story points

Acceptance Criteria: 
- Time series analysis chart available and visible, in addition to the existing charts. 
- Single chart that visually shows the performance of various marketing techniques over time. 
- Interactive elements such as zoom, pan, zoom in, zoom out available and functional. 
- Chart includes tools for detecting seasonality patterns (around a particular time of the year, etc)

**Comment by saurabhsainani** [comment]
@ivm25 Do we need to make any changes to the acceptance criteria?

**Comment by ivm25** [comment]
@saurabhsainani : Only the last point could be removed or maybe tweaked, as I wont be able to do trend lines on that. It might be a little less than that to start off.

**Comment by saurabhsainani** [comment]
Done

**Comment by ivm25** [comment]
@saurabhsainani , I have added time series charts, that are now visible on the bottom right corner of the dashboard and they display:

1. Actual data as a function of time.
2. The trend of the data as a function of time
3. Seasonality of the data (that can be expressed as a function of different periods) and understood differently.
4. Residuals (Revenue that is largely impacted by marketing or media channels)
- There is a dropdown that allows you to change the period (for example period = 4 would mean every four weeks, there is a seasonal change in the data)

**Comment by saurabhsainani** [comment]
@ivm25 The charts work well!
