### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by saurabhsainani** [ivm25/marketing_mix_modelling#6]
- Instructions (if needed) for the data input.
- Manual to guide a first time user. 
- Documentation to support a user to navigate the charts and tables easily.

**Comment by ivm25** [comment]
@saurabhsainani , I have added an **instructions.md** (A Markdown file) file **within the repository** that tackles:
- The type of input data, a user needs to provide. What happens in case of any differences.
- There are general instructions included as well to allow setup for a new user.
- I have not yet included a documentation to navigate charts separately, but I wanted to make it super clear within the dashboard. So, if that is not yet clear, I can do that.
- You should be able to click on it and it should open within the browser.

**Comment by saurabhsainani** [comment]
@ivm25 The instructions are pretty clear! The links are particularly helpful. 
Navigating the charts is already super clear from the dashboard, so we ideally should not need any additional documentation for that.
