### ISSUE TITLE
As a business stakeholder, I want a variety of visualization tools for large datasets so that I can analyze the performance of various marketing channels over time.

### ISSUE THREAD

**Issue by saurabhsainani** [ivm25/marketing_mix_modelling#7]
Estimation: 
13 story points

Acceptance criteria: 
- Heatmap chart highlighting the performance and interaction of various marketing channels over time available and functional. 
- Chart includes color intensity representation to help better visualize the performance of marketing channels over time.

**Comment by ivm25** [comment]
@saurabhsainani , I have included a heatmap type chart:
1. That can be used to understand the distribution of data (marketing channels data as a function of revenue).
2. The heatmap colour index represents a count of 'how many weeks' had x amount of revenue or y amount of marketing spend (over time).
3. The violin charts on top and right ae indicators to understand if data is having outliers or not. You can hover on them and view descriptive stats.

**Comment by saurabhsainani** [comment]
@ivm25 Works well!
